
exec-once = /nix/store/5gln2rkcjx93cr5x0rr3wqrxjdmshd2f-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
bind=SUPER SHIFT, Q, exec, uwsm stop
bind=SUPER, Q, killactive
# Doesn't seem to be working
bind=SUPER , ESC, exec, loginctl lock-session
# Duplicate all h,j,k,l binds with arrows as well
bind=SUPER, H, movefocus, l
bind=SUPER, J, movefocus, d
bind=SUPER, K, movefocus, u
bind=SUPER, L, movefocus, r
bind=SUPER SHIFT, H, movewindow, l
bind=SUPER SHIFT, J, movewindow, d
bind=SUPER SHIFT, K, movewindow, u
bind=SUPER SHIFT, L, movewindow, r
bind=SUPER CTRL, K, workspace, -1
bind=SUPER CTRL, J, workspace, +1
bind=SUPER CTRL SHIFT, K, movetoworkspace, -1
bind=SUPER CTRL SHIFT, J, movetoworkspace, +1
# Having both of these seems redundant. Keep M
bind=SUPER, M, fullscreen, 1
bind=SUPER ALT, Space, fullscreen, 1
bind=SUPER, F, togglefloating
bind=SUPER, Space, fullscreen, 0
bind=SUPER, W, layoutmsg, colresize +conf
bind=SUPER ALT, H, layoutmsg, consume_or_expel prev
bind=SUPER ALT, L, layoutmsg, consume_or_expel next
bind=SUPER, Return, exec, ghostty
bind=SUPER, B, exec, zen-twilight
bind=SUPER, D, exec, dms ipc call spotlight toggle
bind=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=, XF86AudioPrev, exec, playerctl previous
bind=, XF86AudioPlay, exec, playerctl play-pause
bind=, XF86AudioNext, exec, playerctl next
bind=, Print, exec, hypr-screenshot copy-area
bind=SHIFT, Print, exec, hypr-screenshot save-area
bind=CTRL, Print, exec, hypr-screenshot save-screen
bind=SUPER, Print, exec, hypr-record toggle-area
bind=SUPER SHIFT, Print, exec, hypr-record toggle-screen
bind=SUPER CTRL, Print, exec, hypr-record stop

bindm=SUPER, mouse:272, movewindow
bindm=SUPER, mouse:273, resizewindow

decoration {
  rounding=4
  rounding_power=4

  inactive_opacity=0.90
  dim_inactive=true
  dim_strength=0.40

  blur {
    enabled=true
    size=8
    passes=1
    new_optimizations=true
  }
}

general {
  border_size=1
  gaps_in=4
  gaps_out=4
  col.active_border=rgb(2ac3de)
  col.inactive_border=rgb(444b6a)
  layout=scrolling
  resize_on_border=false
}

group {
  groupbar {
    col.active=rgb(2ac3de)
    col.inactive=rgb(444b6a)
    text_color=rgb(a9b1d6)
  }
  col.border_active=rgb(2ac3de)
  col.border_inactive=rgb(444b6a)
  col.border_locked_active=rgb(b4f9f8)
}

input {
  touchpad {
    disable_while_typing=true
    natural_scroll=true
middle_button_emulation=true
  }
  follow_mouse=1
  kb_layout=us
  repeat_rate=25
  repeat_delay=600
  sensitivity=0.0
}

misc {
  background_color=rgb(1a1b26)
}

scrolling {
  column_width=0.500000
  focus_fit_method=1
  follow_focus=true
  fullscreen_on_one_column=true
  wrap_focus=true
  wrap_swapcol=true
}

xwayland {
  force_zero_scaling=true
}

# Laptop screen
monitor = eDP-1, 1920x1080@300.01, 0x0, 1
# Generic rule for plugged in monitors
monitor = , preferred, auto, 1
